[package]
name = "pbc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
inkwell = {version = "0.5.0", features = ["llvm18-0"]}
thiserror = "2.0.12"
